// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf2GInqfFoa9wJHuii3DKLU3H5PaMk-DI',
    appId: '1:944125752467:web:324d1f213b8ecf11d34966',
    messagingSenderId: '944125752467',
    projectId: 'cloudstore-619',
    authDomain: 'cloudstore-619.firebaseapp.com',
    storageBucket: 'cloudstore-619.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnJ0t2fE0D7l30atPVTI1_bpVYFYVPcSM',
    appId: '1:944125752467:android:a803be19656a64bdd34966',
    messagingSenderId: '944125752467',
    projectId: 'cloudstore-619',
    storageBucket: 'cloudstore-619.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs89nJ61qm-lUFchzSybmYT8OdbsL6K_Y',
    appId: '1:944125752467:ios:7e95c19f995d75c1d34966',
    messagingSenderId: '944125752467',
    projectId: 'cloudstore-619',
    storageBucket: 'cloudstore-619.appspot.com',
    iosClientId: '944125752467-chaf1lvbjiq6906tdeju2ova2aua0864.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs89nJ61qm-lUFchzSybmYT8OdbsL6K_Y',
    appId: '1:944125752467:ios:7e95c19f995d75c1d34966',
    messagingSenderId: '944125752467',
    projectId: 'cloudstore-619',
    storageBucket: 'cloudstore-619.appspot.com',
    iosClientId: '944125752467-chaf1lvbjiq6906tdeju2ova2aua0864.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudstore',
  );
}
